apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
data:
  # MySQL Config
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_NAME: "airbnb_db"
  
  # MongoDB Config
  MONGO_INITDB_DATABASE: "airbnb"
  
  # Kafka Config
  KAFKA_BROKER: "kafka-service:9092"
  
  # Zookeeper Config
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  
  # Kafka Environment
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  
  # Backend Config
  NODE_ENV: "production"
  PORT: "5000"
