apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secrets
type: Opaque
stringData:
  # MySQL
  MYSQL_ROOT_PASSWORD: "Lappy1234567890"
  MYSQL_DATABASE: "airbnb_db"
  
  # MongoDB
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin123"
  
  # Session
  SESSION_SECRET: "cmpe273_airbnb_secret_key_2024"
  
  # Database Connection Strings
  MONGODB_URI: "mongodb://admin:admin123@mongodb-service:27017/airbnb?authSource=admin"
